---
- ansible.builtin.assert:
    that:
      - target_jboss_home is defined
      - previous_jboss_eap_home is defined
    quiet: True
    fail_msg: "Missing required parameters."

- ansible.builtin.set_fact:
    migration_tool: "{{ target_jboss_home }}/bin/jboss-server-migration.sh"

- ansible.builtin.stat:
    path: "{{ migration_tool }}"
  register: migration_tool_state

- ansible.builtin.assert:
    that:
      - migration_tool_state is defined
      - migration_tool_state.stat is defined
      - migration_tool_state.stat.exists is defined
      - migration_tool_state.stat.exists
      - migration_tool_state.stat.isreg is defined
      - migration_tool_state.stat.isreg
    quiet: True
    fail_msg: "Invalid path to migration tool: {{ migration_tool }}."

- name: "Ensures migration configuration is deployed"
  ansible.builtin.template:
    src: "{{ wildfly_migration_environment_props }}"
    dest: "{{ target_jboss_home }}/migration/configuration/environment.properties"

- name: "Run migration tool"
  ansible.builtin.command: "{{ migration_tool }} --non-interactive --source {{ previous_jboss_eap_home }} --environment {{ target_jboss_home }}/migration/configuration/environment.properties"
  register: migration_results
  changed_when:
    - '"Migration Result: SUCCESS" in migration_results.stdout'

- name: "Display results of migration"
  ansible.builtin.debug:
    msg: "{{ migration_results }}"
  changed_when: False
  when:
    - '"Migration Result: SUCCESS" in migration_results.stdout'
