---
- name: EAP {{ eap_source_version }} to {{ target_eap_version }} migration playbook
  hosts: all
  vars:
    eap_source_version: 7.2
    target_eap_version: 7.3
    eap_configuration_file: jboss_eap.xml
    installed_eap_source: True
    migrated_jboss_eap_home: "/opt/jboss_eap/jboss-eap-{{ target_eap_version }}/"
    # vars for target EAP, installed with zipfle
    target_jboss_eap_home: /opt/rh/eap7/root/usr/share/wildfly/
    skip_group_remove: False
    jboss_eap_service_name: jboss_eap
    jboss_eap_systemd_service_name: "{{ jboss_eap_service_name }}.service"
  vars_files:
    - vars/eap_system_info.yml
  collections:
    - redhat.jboss_eap
  pre_tasks:

    - name: "Populate service facts"
      ansible.builtin.service_facts:

    - name: "Check if service is running"
      ansible.builtin.command: "systemctl stop {{ jboss_eap_service_name }}"
      when:
        - ansible_facts is defined
        - ansible_facts.services is defined
        - ansible_facts.services[jboss_eap_systemd_service_name] is defined
        - ansible_facts.services[jboss_eap_systemd_service_name]['state'] is defined
        - ansible_facts.services[jboss_eap_systemd_service_name]['state'] == 'running'

    - name: "Ensure EAP {{ eap_source_version }} has been removed."
      ansible.builtin.include_role:
        name: jboss_eap_subs
        tasks_from: disable_repo.yml
      vars:
        eap_version: "{{ eap_source_version }}"

    - name: "Ensure EAP {{ target_eap_version }} has been installed."
      ansible.builtin.include_role:
        name: jboss_eap_subs
      vars:
        eap_version: "{{ target_eap_version }}"

  tasks:
    - ansible.builtin.set_fact:
        migration_state_file: /opt/rh/eap7/root/usr/share/wildfly/migration/.migrated

    - name: "Load migration state file data"
      ansible.builtin.stat:
        path: "{{ migration_state_file }}"
      register: is_migration_done

    - ansible.builtin.assert:
        that:
          - is_migration_done is defined
          - is_migration_done.stat is defined
          - is_migration_done.stat.exists is defined
        quiet: True
        fail_msg: "Failed to retrieve metadata on migration state file: {{ migration_state_file }}."

    - block:

        - ansible.builtin.set_fact:
            migrated_conf: "{{ migrated_jboss_eap_home }}/standalone/configuration/{{ eap_configuration_file }}"
            target_conf: "{{ target_jboss_eap_home }}/standalone/configuration/{{ eap_configuration_file }}"

        - name: "Copy migrated configuration from {{ migrated_conf }} file to target {{ target_conf }}."
          ansible.builtin.copy:
            src: "{{ migrated_conf }}"
            dest: "{{ target_conf }}"
            owner: "{{ jboss_eap_user }}"
            group: "{{ jboss_eap_group }}"
            mode: '0644'
            remote_src: True

        - name: "Ensures 'rsync' is installed."
          ansible.builtin.package:
            name: rsync
            state: present

        - name: "Synchronize custom modules"
          ansible.posix.synchronize:
            src: "{{ migrated_jboss_eap_home }}/modules"
            dest: "{{ target_jboss_eap_home }}/"
            copy_links: no
            rsync_opts:
              - "--exclude {{ migrated_jboss_eap_home }}/modules/system"

        - name: "Ensures state file exists"
          ansible.builtin.file:
            path: "{{ migration_state_file }}"
            state: touch
            modification_time: preserve
            access_time: preserve

      rescue:
        - name: "Migration has failed."
          ansible.builtin.debug:
            msg: "Migration has failed."
      when:
        - not is_migration_done.stat.exists

    - ansible.builtin.debug:
        msg: "Server has already been migrated."
      when:
        - is_migration_done.stat.exists
  post_tasks:

    - name: "Ensures JBoss EAP {{ target_eap_version }} is running"
      ansible.builtin.include_role:
        name: jboss_eap_systemd
      vars:
        jboss_eap_home: "{{ target_jboss_eap_home }}"
        jboss_eap_systemd_enabled: True
