---
- name: EAP {{ eap_source_version }} to {{ target_eap_version }} migration playbook
  hosts: localhost
  vars:
    eap_source_version: 7.2
    target_eap_version: 7.3
    previous_jboss_eap_home: /opt/rh/eap7/root/usr/share/wildfly/
    target_zipfile: "jboss-eap-{{ target_eap_version }}.0.zip"
    target_jboss_install_dir: /opt/jboss_eap/
    target_jboss_home: "{{ target_jboss_install_dir }}/jboss-eap-{{ target_eap_version }}/"
  vars_files:
    - vars/jdbc_driver.yml
  collections:
    - redhat.jboss_eap
  pre_tasks:
    - name: "Ensures required dependencies are installed."
      ansible.builtin.package:
        name: unzip
        state: present

    - name: "Ensures {{ target_jboss_install_dir }} exists."
      ansible.builtin.file:
        path: "{{ target_jboss_install_dir }}"
        state: directory

    - name: "Ensures new EAP version {{ target_zipfile }} has been unarchive into {{ target_jboss_install_dir }}"
      ansible.builtin.unarchive:
        src: "{{ target_zipfile }}"
        dest: "{{ target_jboss_install_dir }}"
        creates: "{{ target_jboss_home }}/bin/standalone.sh"

  tasks:
    - name: "Peform migration from {{ previous_jboss_eap_home }} to {{ target_jboss_home }}."
      ansible.builtin.include_role:
        name: wildfly_migration
