---
- name: Ensures EAP {{ eap_source_version }} is installed and configured
  hosts: localhost
  vars:
    # vars for source, rpm based installed
    eap_source_version: 7.2
    jboss_eap_group_install_name: jboss-eap7-jdk11
    installed_eap_source: True
    jboss_eap_home: /opt/rh/eap7/root/usr/share/wildfly/
  vars_files:
    - vars/jdbc_driver.yml
    - vars/eap_system_info.yml
  collections:
    - redhat.jboss_eap
  tasks:

    - name: "Ensure EAP {{ eap_source_version }} is installed."
      ansible.builtin.include_role:
        name: wildfly_subs
      vars:
        eap_version: "{{ eap_source_version }}"

    - name: "Install Maria DB driver in {{ jboss_eap_home }}"
      ansible.builtin.include_role:
        name: wildfly_driver
      vars:
        jdbc_driver_jar_url: "https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/{{ jdbc_driver_version }}/mariadb-java-client-{{ jdbc_driver_version }}.jar"

    - name: "Ensures JBoss EAP {{ eap_source_version }} is running"
      ansible.builtin.include_role:
        name: wildfly_systemd
      vars:
        wildfly_home: "{{ jboss_eap_home }}"
        wildfly_systemd_enabled: True

    - ansible.builtin.set_fact:
        path_to_driver: "{{ jdbc_driver_module_dir }}/{{ jdbc_driver_jar_filename }}"

    - block:
      - name: "Checks if MariaDB driver is activated"
        ansible.builtin.include_role:
          name: wildfly_utils
          tasks_from: jboss_cli.yml
        vars:
          jboss_home: "{{ jboss_eap_home }}"
          query: "/subsystem=datasources/jdbc-driver={{ jdbc_driver_module_name }}:read-resource"
      rescue:

      - name: "Deploy MariaDB driver is activated"
        ansible.builtin.include_role:
          name: wildfly_utils
          tasks_from: jboss_cli.yml
        vars:
          jboss_home: "{{ jboss_eap_home }}"
          query: "{{ item }}"
        loop:
          - "'/subsystem=datasources/jdbc-driver={{ jdbc_driver_module_name }}:add(driver-name={{ jdbc_driver_module_name }}, driver-module-name={{ jdbc_driver_module_name }}, driver-class-name=org.mariadb.jdbc.Driver)'"
          - "'data-source add --jndi-name=java:/MariaDS --name=MariaDBPool --connection-url=jdbc:mariadb://mariadb:5432/db --driver-name={{ jdbc_driver_module_name }}'"
          - ":write-config()"
