---
- name: Ensures EAP {{ eap_version }} is installed and configured
  hosts: localhost
  vars:
    # vars for source, rpm based installed
    eap_version: 7.4
    jboss_eap_group_install_name: jboss-eap7-jdk11
    jboss_eap_home: /opt/rh/eap7/root/usr/share/wildfly/
    skip_disable_eap74: True
    wildfly_enable_yml_config: yes
    wildfly_yml_configs:
      - eap_config.yml
  vars_files:
    - vars/jdbc_driver.yml
    - vars/eap_system_info.yml
  collections:
    - redhat.jboss_eap
  tasks:

    - name: "Ensure EAP {{ eap_source_version }} is installed."
      ansible.builtin.include_role:
        name: wildfly_subs

    - name: "Install Maria DB driver in {{ jboss_eap_home }}"
      ansible.builtin.include_role:
        name: wildfly_driver
      vars:
        jdbc_driver_jar_url: "https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/{{ jdbc_driver_version }}/mariadb-java-client-{{ jdbc_driver_version }}.jar"

    - name: "Ensure JBoss EAP configuration file is deployed."
      ansible.builtin.template:
        src: templates/eap_config.yml.j2
        dest: "{{ jboss_eap_home }}/standalone/eap_config.yml"
        owner: "{{ wildfly_user }}"
        group: "{{ wildfly_group }}"

    - name: "Ensures JBoss EAP {{ eap_source_version }} is running"
      ansible.builtin.include_role:
        name: wildfly_systemd
      vars:
        wildfly_home: "{{ jboss_eap_home }}"
        wildfly_systemd_enabled: True
