---
- name: Prepare
  hosts: all
  tasks:
    - ansible.builtin.set_fact:
        down_server: "{{ lookup('env','MIDDLEWARE_DOWNLOAD_RELEASE_SERVER_URL') }}"

    - ansible.builtin.assert:
        that:
          - down_server is defined
          - down_server | length > 0
        quiet: True

    - name: "Download JBoss EAP zipfile from {{ down_server }}//eap7/7.4.0/jboss-eap-7.4.0.zip"
      get_url:
        url: "{{ down_server }}//eap7/7.4.0/jboss-eap-7.4.0.zip"
        dest: /opt/jboss-eap-7.4.0.zip
      loop:
        - 7.3
        - 7.4
      loop_control:
        loop_var: jboss_version

